# This file is automatically generated
from cygraphblas_ss cimport _lib as lib

DIAG = lib.DIAG
EQ_THUNK = lib.EQ_THUNK
EQ_ZERO = lib.EQ_ZERO
GE_THUNK = lib.GE_THUNK
GE_ZERO = lib.GE_ZERO
GT_THUNK = lib.GT_THUNK
GT_ZERO = lib.GT_ZERO
LE_THUNK = lib.LE_THUNK
LE_ZERO = lib.LE_ZERO
LT_THUNK = lib.LT_THUNK
LT_ZERO = lib.LT_ZERO
NE_THUNK = lib.NE_THUNK
NONZERO = lib.NONZERO
OFFDIAG = lib.OFFDIAG
TRIL = lib.TRIL
TRIU = lib.TRIU