# This file is automatically generated
from cygraphblas_ss cimport _clib as clib

DIAG = clib.DIAG
EQ_THUNK = clib.EQ_THUNK
EQ_ZERO = clib.EQ_ZERO
GE_THUNK = clib.GE_THUNK
GE_ZERO = clib.GE_ZERO
GT_THUNK = clib.GT_THUNK
GT_ZERO = clib.GT_ZERO
LE_THUNK = clib.LE_THUNK
LE_ZERO = clib.LE_ZERO
LT_THUNK = clib.LT_THUNK
LT_ZERO = clib.LT_ZERO
NE_THUNK = clib.NE_THUNK
NONZERO = clib.NONZERO
OFFDIAG = clib.OFFDIAG
TRIL = clib.TRIL
TRIU = clib.TRIU