# This file is automatically generated
from cygraphblas_ss cimport _clib as clib

COMPLETE = clib.COMPLETE
COMPLETE_VERBOSE = clib.COMPLETE_VERBOSE
SHORT = clib.SHORT
SHORT_VERBOSE = clib.SHORT_VERBOSE
SILENT = clib.SILENT
SUMMARY = clib.SUMMARY