# This file is automatically generated
from cygraphblas_ss cimport _clib as clib

THREAD_ANSI = clib.THREAD_ANSI
THREAD_NONE = clib.THREAD_NONE
THREAD_OPENMP = clib.THREAD_OPENMP
THREAD_POSIX = clib.THREAD_POSIX
THREAD_WINDOWS = clib.THREAD_WINDOWS