# This file is automatically generated
from cygraphblas cimport _lib as lib

BOOL = lib.BOOL
FP32 = lib.FP32
FP64 = lib.FP64
INT16 = lib.INT16
INT32 = lib.INT32
INT64 = lib.INT64
INT8 = lib.INT8
UINT16 = lib.UINT16
UINT32 = lib.UINT32
UINT64 = lib.UINT64
UINT8 = lib.UINT8