# This file is automatically generated
from .. cimport _lib

BOOL = _lib.BOOL
FP32 = _lib.FP32
FP64 = _lib.FP64
INT16 = _lib.INT16
INT32 = _lib.INT32
INT64 = _lib.INT64
INT8 = _lib.INT8
UINT16 = _lib.UINT16
UINT32 = _lib.UINT32
UINT64 = _lib.UINT64
UINT8 = _lib.UINT8